version: '3.7'
services:
  postgres:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: p4ssword
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    networks:
      - intranet
  kratos-migrate:
    depends_on:
      - postgres
    image: oryd/kratos:v0.10.1
    environment:
      - DSN=postgres://postgres:p4ssword@postgres:5432/postgres
    volumes:
      - type: bind
        source: ./kratos-config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.10.1
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://localhost:4433/
      - PORT=4455
      - SECURITY_MODE=
    networks:
      - intranet
    restart: on-failure
    ports:
      - "4455:4455"
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.10.1
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://postgres:p4ssword@postgres:5432/postgres
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./kratos-config
        target: /etc/config/kratos
    networks:
      - intranet
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet
networks:
  intranet:
volumes:
  kratos-sqlite:
